### ISSUE TITLE
[Question] TNS crossmatching

### ISSUE THREAD

**Issue by panos-charalampopoulos** [alercebroker/alerce_client#42]
*programming*

Hello,
I am trying the API in order to query some transients and it's working well!

Is there any way to crossmatch the returned data with TNS in order to avoid getting already classified transients? Or in general, is there maybe a flag that informs the user if a transient is already classified?

Many thanks in advance!

**Comment by panos-charalampopoulos** [comment]
Any updates on this?

**Comment by ignacioreyes** [comment]
Hi!
Currently, we don't have a flag in our database that indicates if an object has been confirmed in TNS. The TNS info displayed in alerce.online is being queried to TNS on the spot.
If you want to filter objects with TNS classification you will have to download the object list from TNS and then do the filtering manually. 
Cheers,

Ignacio

**Comment by fforster** [comment]
Note that in order to download a csv file from the TNS website that you need a TNS account (see https://www.wis-tns.org/content/tns-getting-started#Daily%20CSV%20staging). If you are unable to do so please let us know and we could populate a table daily, but this will not be up to date with the latest classifications and it will take some time for our engineering team to develop and put in production.
